[package]
name = "mcp-core"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
rmcp = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
utoipa = "4.1"

[dev-dependencies]
tempfile = "3.8"
