services:
  goose-cli:
    build:
      context: ../../..
      dockerfile: documentation/docs/docker/Dockerfile
      args:
        USER_ID: ${UID:-1000}
    volumes:
      # Mount user's directory with read-write access
      - ../../..:/root/workspace
      - goose-config:/root/.goose
      # Mount git config
      - ~/.gitconfig:/root/.gitconfig:ro
      # Mount SSH keys
      - ~/.ssh:/root/.ssh:ro
    working_dir: /root/workspace
    environment:
      - OOSE_HOME=/root/.goose
      # Set default editor
      - EDITOR=vim
      # Preserve git author info
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-Goose User}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-goose@example.com}
      # Set GOOGLE_API_KEY to your own API key
      - GOOGLE_API_KEY="XXX"
      - GOOSE_PROVIDER=google
      - GOOSE_MODEL=gemini-2.0-flash-exp
      - DBUS_SESSION_BUS_ADDRESS
      - GNOME_KEYRING_CONTROL
      - SSH_AUTH_SOCK
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]

volumes:
  goose-config: